package br.inatel.debug_doctors.domain;

import br.inatel.debug_doctors.domain.patient.Patient;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PatientTest {

    @Test
    void shouldCreatePatientWithCorrectData() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");
        patient.setCpf("123.456.789-00");
        patient.setEmail("john@email.com");

        // Assert
        assertEquals("John Silva", patient.getName());
        assertEquals("123.456.789-00", patient.getCpf());
        assertEquals("john@email.com", patient.getEmail());
    }

    @Test
    void shouldUpdatePatientName() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");

        // Act
        patient.setName("Carlos Souza");

        // Assert
        assertEquals("Carlos Souza", patient.getName());
    }

    @Test
    void shouldUpdatePatientEmail() {
        // Arrange
        Patient patient = new Patient();
        patient.setEmail("john@email.com");

        // Act
        patient.setEmail("carlos@email.com");

        // Assert
        assertEquals("carlos@email.com", patient.getEmail());
    }

    @Test
    void shouldCreateEmptyPatientWithDefaultConstructor() {
        // Arrange + Act
        Patient patient = new Patient();

        // Assert
        assertNull(patient.getName());
        assertNull(patient.getCpf());
        assertNull(patient.getEmail());
    }

    @Test
    void shouldCreatePatientUsingAllArgsConstructor() {
        // Arrange & Act: Create the patient passing all data (ID, Name, CPF, Email)
        Patient patient = new Patient(1L, "Camila Silva", "111.222.333-44", "camila@email.com");

        // Assert: Verify if everything was mapped to the correct attributes
        assertEquals(1L, patient.getId());
        assertEquals("Camila Silva", patient.getName());
        assertEquals("111.222.333-44", patient.getCpf());
        assertEquals("camila@email.com", patient.getEmail());
    }
    @Test
    void shouldSetAndGetPatientId() {

        Patient patient = new Patient();
        Long simulatedDatabaseId = 500L;


        patient.setId(simulatedDatabaseId);


        assertEquals(simulatedDatabaseId, patient.getId(), "The patient ID must be the same as the one generated by the database.");
    }



    private static class PatientMock extends Patient {
        private final String name;
        private final String email;
        private final String cpf;

        PatientMock(String name, String email, String cpf) {
            this.name = name;
            this.email = email;
            this.cpf = cpf;
        }

        @Override
        public String getName() { return name; }

        @Override
        public String getEmail() { return email; }

        @Override
        public String getCpf() { return cpf; }
    }

    private static class PatientBusinessValidator {
        void validateEmail(Patient patient) {
            String email = patient.getEmail();
            if (email == null || !email.contains("@")) {
                throw new IllegalArgumentException("The provided email is invalid");
            }
        }

        void validateCpf(Patient patient) {
            String cpf = patient.getCpf();
            if (cpf == null || cpf.length() != 14) {
                throw new IllegalArgumentException("The CPF must contain 14 characters including punctuation");
            }
        }
    }


    @Test
    void shouldReturnMockedPatientName() {
        Patient fakePatient = new PatientMock("Mocked Patient Name", "mocked@email.com", "000.000.000-00");
        assertEquals("Mocked Patient Name", fakePatient.getName(), "The mock should return the fake name");
    }

    @Test
    void shouldReturnMockedPatientEmailAndCpf() {
        Patient fakePatient = new PatientMock("Mocked Patient Name", "mocked@email.com", "000.000.000-00");
        assertEquals("mocked@email.com", fakePatient.getEmail(), "The mock should return the fake email");
        assertEquals("000.000.000-00", fakePatient.getCpf(), "The mock should return the fake cpf");
    }


    @Test
    void shouldThrowExceptionWhenPatientEmailIsInvalid() {
        Patient mockedPatient = new PatientMock("Augusto", "augustohospital.com", "111.222.333-44");
        PatientBusinessValidator validator = new PatientBusinessValidator();

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> validator.validateEmail(mockedPatient)
        );

        assertEquals("The provided email is invalid", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenPatientCpfIsTooShort() {
        Patient mockedPatient = new PatientMock("Augusto", "augusto@hospital.com", "123");
        PatientBusinessValidator validator = new PatientBusinessValidator();

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> validator.validateCpf(mockedPatient)
        );

        assertEquals("The CPF must contain 14 characters including punctuation", exception.getMessage());
    }

    @Test
    void shouldValidatePatientWithValidData() {
        Patient mockedPatient = new PatientMock("Augusto", "augusto@hospital.com", "111.222.333-44");
        PatientBusinessValidator validator = new PatientBusinessValidator();


        validator.validateEmail(mockedPatient);
        validator.validateCpf(mockedPatient);
    }
}