package br.inatel.debug_doctors.domain;

import br.inatel.debug_doctors.domain.patient.Patient;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PatientTest {

    @Mock
    private Patient mockedPatient;

    // -------------------------------------------------------------------------
    // Testes da entidade real — sem mock, pois testam o próprio comportamento
    // -------------------------------------------------------------------------

    @Test
    void shouldCreatePatientWithCorrectData() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");
        patient.setCpf("123.456.789-00");
        patient.setEmail("john@email.com");

        // Assert
        assertEquals("John Silva", patient.getName());
        assertEquals("123.456.789-00", patient.getCpf());
        assertEquals("john@email.com", patient.getEmail());
    }

    @Test
    void shouldUpdatePatientName() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");

        // Act
        patient.setName("Carlos Souza");

        // Assert
        assertEquals("Carlos Souza", patient.getName());
    }

    @Test
    void shouldUpdatePatientEmail() {
        // Arrange
        Patient patient = new Patient();
        patient.setEmail("john@email.com");

        // Act
        patient.setEmail("carlos@email.com");

        // Assert
        assertEquals("carlos@email.com", patient.getEmail());
    }

    @Test
    void shouldCreateEmptyPatientWithDefaultConstructor() {
        // Arrange + Act
        Patient patient = new Patient();

        // Assert
        assertNull(patient.getName());
        assertNull(patient.getCpf());
        assertNull(patient.getEmail());
    }

    @Test
    void shouldCreatePatientUsingAllArgsConstructor() {
        // Arrange & Act
        Patient patient = new Patient(1L, "Camila Silva", "111.222.333-44", "camila@email.com");

        // Assert
        assertEquals(1L, patient.getId());
        assertEquals("Camila Silva", patient.getName());
        assertEquals("111.222.333-44", patient.getCpf());
        assertEquals("camila@email.com", patient.getEmail());
    }

    @Test
    void shouldSetAndGetPatientId() {
        Patient patient = new Patient();
        Long simulatedDatabaseId = 500L;

        patient.setId(simulatedDatabaseId);

        assertEquals(simulatedDatabaseId, patient.getId(),
                "The patient ID must be the same as the one generated by the database.");
    }

    // -------------------------------------------------------------------------
    // Testes com Mockito — simulam dependências externas ao Patient
    // (ex: quando um serviço vai buscar os dados do paciente sem acessar o DB)
    // -------------------------------------------------------------------------

    @Test
    void shouldReturnPatientDataFromMock() {
        // Arrange: configura o mock para retornar dados sem instanciar a classe real
        when(mockedPatient.getName()).thenReturn("Maria Oliveira");
        when(mockedPatient.getCpf()).thenReturn("987.654.321-00");
        when(mockedPatient.getEmail()).thenReturn("maria@email.com");

        // Act
        String name = mockedPatient.getName();
        String cpf = mockedPatient.getCpf();
        String email = mockedPatient.getEmail();

        // Assert
        assertEquals("Maria Oliveira", name);
        assertEquals("987.654.321-00", cpf);
        assertEquals("maria@email.com", email);

        // Verifica que os getters foram realmente chamados uma vez
        verify(mockedPatient, times(1)).getName();
        verify(mockedPatient, times(1)).getCpf();
        verify(mockedPatient, times(1)).getEmail();
    }

    @Test
    void shouldReturnNullFieldsWhenPatientNotConfigured() {
        // Mockito retorna null por padrão para objetos não configurados
        when(mockedPatient.getName()).thenReturn(null);
        when(mockedPatient.getCpf()).thenReturn(null);
        when(mockedPatient.getEmail()).thenReturn(null);

        assertNull(mockedPatient.getName(), "Name should be null when not configured");
        assertNull(mockedPatient.getCpf(), "CPF should be null when not configured");
        assertNull(mockedPatient.getEmail(), "Email should be null when not configured");

        verify(mockedPatient).getName();
        verify(mockedPatient).getCpf();
        verify(mockedPatient).getEmail();
    }

    @Test
    void shouldReturnMockedPatientId() {
        // Arrange: simula o retorno de um ID gerado pelo banco de dados
        when(mockedPatient.getId()).thenReturn(500L);

        // Act
        Long id = mockedPatient.getId();

        // Assert
        assertEquals(500L, id, "The mocked ID should be 500");
        verify(mockedPatient, times(1)).getId();
    }
}