package br.inatel.debug_doctors.domain;

import br.inatel.debug_doctors.domain.patient.Patient;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PatientTest {

    @Test
    void shouldCreatePatientWithCorrectData() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");
        patient.setCpf("123.456.789-00");
        patient.setEmail("john@email.com");

        // Assert
        assertEquals("John Silva", patient.getName());
        assertEquals("123.456.789-00", patient.getCpf());
        assertEquals("john@email.com", patient.getEmail());
    }

    @Test
    void shouldUpdatePatientName() {
        // Arrange
        Patient patient = new Patient();
        patient.setName("John Silva");

        // Act
        patient.setName("Carlos Souza");

        // Assert
        assertEquals("Carlos Souza", patient.getName());
    }

    @Test
    void shouldUpdatePatientEmail() {
        // Arrange
        Patient patient = new Patient();
        patient.setEmail("john@email.com");

        // Act
        patient.setEmail("carlos@email.com");

        // Assert
        assertEquals("carlos@email.com", patient.getEmail());
    }

    @Test
    void shouldCreateEmptyPatientWithDefaultConstructor() {
        // Arrange + Act
        Patient patient = new Patient();

        // Assert
        assertNull(patient.getName());
        assertNull(patient.getCpf());
        assertNull(patient.getEmail());
    }

    @Test
    void shouldCreatePatientUsingAllArgsConstructor() {
        // Arrange & Act: Create the patient passing all data (ID, Name, CPF, Email)
        Patient patient = new Patient(1L, "Camila Silva", "111.222.333-44", "camila@email.com");

        // Assert: Verify if everything was mapped to the correct attributes
        assertEquals(1L, patient.getId());
        assertEquals("Camila Silva", patient.getName());
        assertEquals("111.222.333-44", patient.getCpf());
        assertEquals("camila@email.com", patient.getEmail());
    }
    @Test
    void shouldSetAndGetPatientId() {
        // Arrange
        Patient patient = new Patient();
        Long simulatedDatabaseId = 500L;

        // Act
        patient.setId(simulatedDatabaseId);

        // Assert
        assertEquals(simulatedDatabaseId, patient.getId(), "The patient ID must be the same as the one generated by the database.");
    }}