spring.application.name=debug-doctors
server.port=8000
spring.datasource.url=jdbc:postgresql://db:5432/debug-doctors
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update