spring.application.name=debug-doctors
server.port=8000
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/debug-doctors
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.hibernate.format-sql=true